Data Dictionanry and Folder based migration
aws-samples/amazon-quicksight-sdk-proserve pull request #25
Opened 2021-11-25 00:17 UTC by yingliao422

- Update admin_console_lambda.template
- update for data dictionary
- update admin console repo with data dictionary support
- update admin console repo with data dictionary support
- update admin console repo with data dictionary support
- update admin console repo with data dictionary support
- fix lambda schedule and handler
- Update README.md
- Update README.md
- Sample csv files
- QuickSight Refresh Optimizer PR
- updated .gitignore
- Update README.md
- cleanup & minor updates
- Delete Dataset_Refresh_Optimizer directory
- Adding QS dataset refresh optimizer delivery kit
- data dict and folder based migration

2021-12-03 21:36 UTC, ywang103 commented on Migration-scripts/Jupyter Notebook/Functions.ipynb
> +    "def create_group_membership(session, folderid, objectid, objecttype):\n",
you might want to rename it as create_folder_membership.

2021-12-03 21:37 UTC, ywang103 commented on Migration-scripts/Jupyter Notebook/Functions.ipynb
> +   "version": "3.6.13"
please keep it locally.

2021-12-03 21:37 UTC, ywang103 commented on Migration-scripts/Jupyter Notebook/Functions.ipynb
> +   "name": "conda_python3"
please keep it locally.

2021-12-03 21:37 UTC, ywang103 requested changes
Please make the changes by the comments. Thanks

2021-12-04 00:42 UTC, yingliao422 commented
Added a new commit to my fork to address the change requests. Please review again.

2021-12-14 18:06 UTC, ywang103 approved these changes

2021-12-14 18:24 UTC, merged